require('plenary')

local Hooks = require('privymd.hooks')
local Passphrase = require('privymd.core.passphrase')

describe('Hooks', function()
  before_each(function() end)
  describe('toggle_encryption', function()
    it('should detect if inside a block', function() end)
    it('should decrypt the encrypted block contents', function() end)
    it('should encrypt the clear block contents', function() end)
    it('should notify if no recipient to the encryption', function() end)
    it('should leave modified flag untouched', function() end)
  end)
  describe('decrypt_buffer', function()
    it('should leave buffer untouched if no encrypted blocks', function() end)
    it('should decrypt buffer', function() end)
    it('should be resilient to failure on a block', function() end)
    it('should leave modified flag untouched', function() end)
  end)
  describe('encrypt_and_save_buffer', function()
    describe('if no recipient', function()
      it('should not save if not ok', function() end)
      it('should save plaintext if ok', function() end)
    end)
    describe('if no GPG blocks', function()
      it('should save plaintext', function() end)
    end)
    it('should encrypt and save buffer', function() end)
  end)
  describe('clear_passphrase', function()
    it('should wipe passphrase from memory', function()
      math.randomseed(os.time())
      local new_secret = tostring(math.random())

      Passphrase.set(new_secret)
      local cached_passphrase = Passphrase.get()

      assert.is_equals(cached_passphrase, new_secret)
      Hooks.clear_passphrase()
      cached_passphrase = Passphrase.get()

      assert.is_nil(cached_passphrase)
    end)
  end)
end)
